sudo: required
services:
  - docker

before_install:
  - docker build -t imageid -f Dockerfile.dev .

script:
  - docker run -e CI=true imageid npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-1-590184142381"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
